### ISSUE TITLE
use without CActiveRecord / without database for login data

### ISSUE THREAD

**Issue by Niklas-Peter** [DenitS/yii-apiAuth#9]
I think, you could easily make your extension useable without login data in a database.
For example I just have 1 one user (admin), whose credentials can be easily stored in a config file, so you save all the overhead for querying the DB.

However there is at least one problem:
https://github.com/DenitS/yii-apiAuth/blob/8826cb067204bf48e63fcce13b4d68f4e11add09/components/AUserIdentity.php#L63

Here you explicitly use CActiveRecord. OK, I can override this method, but do you rely on CActiveRecord anywhere else or can I safely use a simple subclass of CModel for 'userClass'?

**Comment by DenitS** [comment]
True it's easy to extend the AUserIdentity and override the getUserModel() method, which is the recommended way of doing this. You can configure apiAuth to use the custom userClass in your application config. 

I've tried to stay way from the database in the rest of the extension, so you should be ok IF you use basic auth. Digest authentication does rely on the db for nonces (which is terribly inefficient).
See [AHttpAuthenticatorDigest:153](https://github.com/DenitS/yii-apiAuth/blob/d396ea6ac981de0b438e18bbccb0b447b0f528b9/components/protocols/digest/AHttpAuthenticatorDigest.php#L153) and [ANonce.php](https://github.com/DenitS/yii-apiAuth/blob/d396ea6ac981de0b438e18bbccb0b447b0f528b9/models/ANonce.php)

Improvements here are much welcomed!

**Comment by np28** [comment]
"True it's easy to extend the AUserIdentity and override the getUserModel() method, which is the recommended way of doing this."
However you have to consider, that your new user class supports getAttribute() method. Maybe it is better, if you add an interface for the userClass, so that others can make sure, that their custom implementation of the userClass is supported.

**Comment by DenitS** [comment]
The easiest way to solve that problem is to make sure your custom userClass extends from the [CModel](http://www.yiiframework.com/doc/api/1.1/CModel) (or [CFormModel](http://www.yiiframework.com/doc/api/1.1/CFormModel)) class, like you should if you would replace any CActiveRecord like class with something non-database related. I see no reason to force it anywhere.

**Comment by np28** [comment]
"The easiest way to solve that problem is to make sure your custom userClass extends from the CModel"
No, that is not enough. CModel has e.g. no method "getAttribute()".

**Comment by DenitS** [comment]
You're right. This should help you.

**Comment by Niklas-Peter** [comment]
There is still a related problem: You can not use virtual attributes for 'usernameAttribute' and so on, because you use 'property_exists' for checking, that does not support __get().
Do you see a way to fix it?

**Comment by DenitS** [comment]
You're right.. dumb mistake. This kills the extension for AR models... I'll remove the added property checking. It's kindof redundant anyway.

**Comment by DenitS** [comment]
fixed by #13
